/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windows1 (void)
{
  GtkWidget *windows1;
  GtkWidget *notebookS1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *labels5;
  GtkWidget *labels6;
  GtkWidget *labels7;
  GtkWidget *entry3;
  GtkWidget *labels8;
  GtkWidget *comboboxs1;
  GtkWidget *supps1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *enregs1;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *labels16;
  GtkWidget *labels15;
  GtkWidget *combobox3;
  GtkWidget *entry6;
  GtkWidget *labels13;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *labels18;
  GtkWidget *labels19;
  GtkWidget *labels17;
  GtkWidget *deconnects1;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *saves1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label9;
  GtkWidget *combobox2;
  GtkWidget *comboboxs3;
  GtkWidget *labels1;
  GtkWidget *fixed3;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label18;
  GtkWidget *label13;
  GtkWidget *button2;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label17;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *combobox7;
  GtkWidget *combobox8;
  GtkWidget *label2;
  GtkWidget *empty_notebook_page;
  GtkWidget *label3;
  GtkWidget *label4;

  windows1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windows1, 900, 500);
  gtk_window_set_title (GTK_WINDOW (windows1), _("windows1"));

  notebookS1 = gtk_notebook_new ();
  gtk_widget_show (notebookS1);
  gtk_container_add (GTK_CONTAINER (windows1), notebookS1);
  gtk_widget_set_size_request (notebookS1, -1, 287);
  gtk_container_set_border_width (GTK_CONTAINER (notebookS1), 12);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebookS1), GTK_POS_LEFT);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebookS1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 112, 40);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("Nciri"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 416, 40);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("Sayf"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  labels5 = gtk_label_new (_("NOM "));
  gtk_widget_show (labels5);
  gtk_fixed_put (GTK_FIXED (fixed1), labels5, 24, 48);
  gtk_widget_set_size_request (labels5, 72, 16);

  labels6 = gtk_label_new (_("Prenom"));
  gtk_widget_show (labels6);
  gtk_fixed_put (GTK_FIXED (fixed1), labels6, 312, 40);
  gtk_widget_set_size_request (labels6, 96, 24);

  labels7 = gtk_label_new (_("CIN"));
  gtk_widget_show (labels7);
  gtk_fixed_put (GTK_FIXED (fixed1), labels7, 40, 96);
  gtk_widget_set_size_request (labels7, 48, 24);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 104, 96);
  gtk_widget_set_size_request (entry3, 104, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  labels8 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (labels8);
  gtk_fixed_put (GTK_FIXED (fixed1), labels8, 240, 96);
  gtk_widget_set_size_request (labels8, 144, 24);

  comboboxs1 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxs1);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxs1, 384, 88);
  gtk_widget_set_size_request (comboboxs1, 55, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs1), _("31"));

  supps1 = gtk_button_new ();
  gtk_widget_show (supps1);
  gtk_fixed_put (GTK_FIXED (fixed1), supps1, 376, 408);
  gtk_widget_set_size_request (supps1, 160, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (supps1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("supprimer profile"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  enregs1 = gtk_button_new ();
  gtk_widget_show (enregs1);
  gtk_fixed_put (GTK_FIXED (fixed1), enregs1, 176, 408);
  gtk_widget_set_size_request (enregs1, 160, 45);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (enregs1), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  labels16 = gtk_label_new (_("Sexe"));
  gtk_widget_show (labels16);
  gtk_fixed_put (GTK_FIXED (fixed1), labels16, 16, 136);
  gtk_widget_set_size_request (labels16, 96, 32);

  labels15 = gtk_label_new (_("Email"));
  gtk_widget_show (labels15);
  gtk_fixed_put (GTK_FIXED (fixed1), labels15, 240, 144);
  gtk_widget_set_size_request (labels15, 72, 32);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox3, 104, 136);
  gtk_widget_set_size_request (combobox3, 112, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("femme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("entre les deux"));

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed1), entry6, 328, 144);
  gtk_widget_set_size_request (entry6, 280, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  labels13 = gtk_label_new (_("Contact"));
  gtk_widget_show (labels13);
  gtk_fixed_put (GTK_FIXED (fixed1), labels13, 40, 192);
  gtk_widget_set_size_request (labels13, 88, 24);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed1), entry7, 152, 192);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed1), entry8, 120, 240);
  gtk_widget_set_size_request (entry8, 104, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed1), entry9, 128, 288);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed1), entry10, 208, 328);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  labels18 = gtk_label_new (_("condition m\303\251dicale"));
  gtk_widget_show (labels18);
  gtk_fixed_put (GTK_FIXED (fixed1), labels18, 32, 328);
  gtk_widget_set_size_request (labels18, 192, 32);

  labels19 = gtk_label_new (_("allergie"));
  gtk_widget_show (labels19);
  gtk_fixed_put (GTK_FIXED (fixed1), labels19, 40, 288);
  gtk_widget_set_size_request (labels19, 96, 32);

  labels17 = gtk_label_new (_("IMC"));
  gtk_widget_show (labels17);
  gtk_fixed_put (GTK_FIXED (fixed1), labels17, 40, 240);
  gtk_widget_set_size_request (labels17, 80, 32);

  deconnects1 = gtk_button_new ();
  gtk_widget_show (deconnects1);
  gtk_fixed_put (GTK_FIXED (fixed1), deconnects1, 536, 408);
  gtk_widget_set_size_request (deconnects1, 136, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (deconnects1), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("D\303\251connection"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  saves1 = gtk_button_new ();
  gtk_widget_show (saves1);
  gtk_fixed_put (GTK_FIXED (fixed1), saves1, 8, 408);
  gtk_widget_set_size_request (saves1, 136, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (saves1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("update"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox2, 448, 88);
  gtk_widget_set_size_request (combobox2, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("12"));

  comboboxs3 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxs3);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxs3, 544, 88);
  gtk_widget_set_size_request (comboboxs3, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxs3), "");

  labels1 = gtk_label_new (_("<b><span foreground=\"#1d4457\" size=\"xx-large\" weight=\"heavy\" >PROFILE</span></b>"));
  gtk_widget_show (labels1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookS1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookS1), 0), labels1);
  gtk_widget_set_size_request (labels1, -1, 100);
  gtk_label_set_use_markup (GTK_LABEL (labels1), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebookS1), fixed3);

  label14 = gtk_label_new (_("Jour"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 176, 56);
  gtk_widget_set_size_request (label14, 56, 24);

  label15 = gtk_label_new (_("moi"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 320, 56);
  gtk_widget_set_size_request (label15, 56, 24);

  label16 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 472, 56);
  gtk_widget_set_size_request (label16, 57, 25);

  label18 = gtk_label_new (_("Acteur :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 144, 248);
  gtk_widget_set_size_request (label18, 88, 32);

  label13 = gtk_label_new (_("date de RDV :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 32, 48);
  gtk_widget_set_size_request (label13, 128, 40);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 224, 368);
  gtk_widget_set_size_request (button2, 224, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button2), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox5), label19, FALSE, FALSE, 0);

  label20 = gtk_label_new (_("label20"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 456, 376);
  gtk_widget_set_size_request (label20, 208, 40);

  label17 = gtk_label_new (_("Heure de r\303\251servation :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 88, 128);
  gtk_widget_set_size_request (label17, 168, 48);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 232, 56);
  gtk_widget_set_size_request (spinbutton1, 80, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 376, 56);
  gtk_widget_set_size_request (spinbutton2, 80, 32);

  spinbutton3_adj = gtk_adjustment_new (2018, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3, 536, 56);
  gtk_widget_set_size_request (spinbutton3, 120, 32);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox7, 272, 136);
  gtk_widget_set_size_request (combobox7, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("8h==>8h.30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("8h30==>9h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("9h==>9h.30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("9h30==>10h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("10h==>10h.30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("10h30==>11h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("11h==>11h.30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("11h30==>12h"));

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox8, 240, 240);
  gtk_widget_set_size_request (combobox8, 160, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Kin\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Diet"));

  label2 = gtk_label_new (_("<b><span foreground=\"#1d4457\" size=\"xx-large\" weight=\"heavy\" >RESERVATION</span></b>"));
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookS1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookS1), 1), label2);
  gtk_widget_set_size_request (label2, -1, 100);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebookS1), empty_notebook_page);

  label3 = gtk_label_new (_("<b><span foreground=\"#1d4457\" size=\"xx-large\" weight=\"heavy\" >LES FICHES</span></b>"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookS1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookS1), 2), label3);
  gtk_widget_set_size_request (label3, -1, 100);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebookS1), empty_notebook_page);

  label4 = gtk_label_new (_("<b><span foreground=\"#1d4457\" size=\"xx-large\" weight=\"heavy\" >RECLAMATION</span></b>"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookS1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookS1), 3), label4);
  gtk_widget_set_size_request (label4, -1, 100);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  g_signal_connect ((gpointer) supps1, "clicked",
                    G_CALLBACK (on_supps1_clicked),
                    NULL);
  g_signal_connect ((gpointer) enregs1, "clicked",
                    G_CALLBACK (on_enregs1_clicked),
                    NULL);
  g_signal_connect ((gpointer) deconnects1, "clicked",
                    G_CALLBACK (on_deconnects1_clicked),
                    NULL);
  g_signal_connect ((gpointer) saves1, "clicked",
                    G_CALLBACK (on_saves1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windows1, windows1, "windows1");
  GLADE_HOOKUP_OBJECT (windows1, notebookS1, "notebookS1");
  GLADE_HOOKUP_OBJECT (windows1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windows1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (windows1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (windows1, labels5, "labels5");
  GLADE_HOOKUP_OBJECT (windows1, labels6, "labels6");
  GLADE_HOOKUP_OBJECT (windows1, labels7, "labels7");
  GLADE_HOOKUP_OBJECT (windows1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (windows1, labels8, "labels8");
  GLADE_HOOKUP_OBJECT (windows1, comboboxs1, "comboboxs1");
  GLADE_HOOKUP_OBJECT (windows1, supps1, "supps1");
  GLADE_HOOKUP_OBJECT (windows1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windows1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windows1, image2, "image2");
  GLADE_HOOKUP_OBJECT (windows1, label10, "label10");
  GLADE_HOOKUP_OBJECT (windows1, enregs1, "enregs1");
  GLADE_HOOKUP_OBJECT (windows1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windows1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windows1, image4, "image4");
  GLADE_HOOKUP_OBJECT (windows1, label12, "label12");
  GLADE_HOOKUP_OBJECT (windows1, labels16, "labels16");
  GLADE_HOOKUP_OBJECT (windows1, labels15, "labels15");
  GLADE_HOOKUP_OBJECT (windows1, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (windows1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (windows1, labels13, "labels13");
  GLADE_HOOKUP_OBJECT (windows1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (windows1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (windows1, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (windows1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (windows1, labels18, "labels18");
  GLADE_HOOKUP_OBJECT (windows1, labels19, "labels19");
  GLADE_HOOKUP_OBJECT (windows1, labels17, "labels17");
  GLADE_HOOKUP_OBJECT (windows1, deconnects1, "deconnects1");
  GLADE_HOOKUP_OBJECT (windows1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windows1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windows1, image3, "image3");
  GLADE_HOOKUP_OBJECT (windows1, label11, "label11");
  GLADE_HOOKUP_OBJECT (windows1, saves1, "saves1");
  GLADE_HOOKUP_OBJECT (windows1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windows1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windows1, image1, "image1");
  GLADE_HOOKUP_OBJECT (windows1, label9, "label9");
  GLADE_HOOKUP_OBJECT (windows1, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (windows1, comboboxs3, "comboboxs3");
  GLADE_HOOKUP_OBJECT (windows1, labels1, "labels1");
  GLADE_HOOKUP_OBJECT (windows1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windows1, label14, "label14");
  GLADE_HOOKUP_OBJECT (windows1, label15, "label15");
  GLADE_HOOKUP_OBJECT (windows1, label16, "label16");
  GLADE_HOOKUP_OBJECT (windows1, label18, "label18");
  GLADE_HOOKUP_OBJECT (windows1, label13, "label13");
  GLADE_HOOKUP_OBJECT (windows1, button2, "button2");
  GLADE_HOOKUP_OBJECT (windows1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windows1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windows1, image5, "image5");
  GLADE_HOOKUP_OBJECT (windows1, label19, "label19");
  GLADE_HOOKUP_OBJECT (windows1, label20, "label20");
  GLADE_HOOKUP_OBJECT (windows1, label17, "label17");
  GLADE_HOOKUP_OBJECT (windows1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (windows1, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (windows1, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (windows1, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (windows1, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (windows1, label2, "label2");
  GLADE_HOOKUP_OBJECT (windows1, label3, "label3");
  GLADE_HOOKUP_OBJECT (windows1, label4, "label4");

  return windows1;
}

GtkWidget*
create_attention (void)
{
  GtkWidget *attention;
  GtkWidget *_;
  GtkWidget *fixeds2;
  GtkWidget *labels12;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbuttons1;
  GtkWidget *annulers1;

  attention = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (attention), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (attention), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (attention), FALSE);

  _ = GTK_DIALOG (attention)->vbox;
  gtk_widget_show (_);

  fixeds2 = gtk_fixed_new ();
  gtk_widget_show (fixeds2);
  gtk_box_pack_start (GTK_BOX (_), fixeds2, TRUE, TRUE, 0);

  labels12 = gtk_label_new (_("Vous etre sur !!"));
  gtk_widget_show (labels12);
  gtk_fixed_put (GTK_FIXED (fixeds2), labels12, 48, 16);
  gtk_widget_set_size_request (labels12, 216, 88);

  dialog_action_area1 = GTK_DIALOG (attention)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbuttons1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbuttons1);
  gtk_dialog_add_action_widget (GTK_DIALOG (attention), okbuttons1, GTK_RESPONSE_OK);
  gtk_widget_set_size_request (okbuttons1, 135, 49);
  GTK_WIDGET_SET_FLAGS (okbuttons1, GTK_CAN_DEFAULT);

  annulers1 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annulers1);
  gtk_dialog_add_action_widget (GTK_DIALOG (attention), annulers1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (annulers1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (attention, attention, "attention");
  GLADE_HOOKUP_OBJECT_NO_REF (attention, _, "_");
  GLADE_HOOKUP_OBJECT (attention, fixeds2, "fixeds2");
  GLADE_HOOKUP_OBJECT (attention, labels12, "labels12");
  GLADE_HOOKUP_OBJECT_NO_REF (attention, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (attention, okbuttons1, "okbuttons1");
  GLADE_HOOKUP_OBJECT (attention, annulers1, "annulers1");

  return attention;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed2;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *button1;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (admin), _("admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (admin), fixed2);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 112, 80);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 112, 120);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button1 = gtk_button_new_with_mnemonic (_("connect"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 160, 216);
  gtk_widget_set_size_request (button1, 66, 29);

  g_signal_connect_after ((gpointer) button1, "clicked",
                          G_CALLBACK (on_button1_clicked),
                          NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (admin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (admin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (admin, button1, "button1");

  return admin;
}

